name: one2one_run
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3

  #Ui
  cupertino_icons: ^1.0.3
  flutter_screenutil: ^5.0.0+2
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  pinput: ^1.2.0
  rounded_loading_button: ^2.0.9
  image_picker: ^0.8.4+2
  flutter_conditional_rendering: ^2.0.0
  pinch_zoom_image_last: ^0.4.1
  smooth_page_indicator: ^1.0.0+2

  #Functions
  shared_preferences: ^2.0.8
  google_sign_in: ^5.1.1
  sign_in_with_apple: ^3.2.0
  firebase_messaging: ^10.0.8
  firebase_core: ^1.7.0
  firebase_analytics: "^8.3.0"
  intl: ^0.17.0
  share_plus: ^3.0.2
  path_provider: ^2.0.5
  signal_r:
    path: signalr_client

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/faq_helper/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Black.ttf